name: Frontend

on:
    workflow_call:
        inputs:
            branch:
                description: "Branch"
                required: false
                type: string
                default: ""
            node:
                description: "Node.js version"
                required: true
                type: string

jobs:
    frontend:
        runs-on: ubuntu-latest
        name: "NodeJS ${{ inputs.node }}"

        env:
            APP_ENV: test_cached
            DATABASE_URL: "mysql://root:root@127.0.0.1/sylius?charset=utf8mb4&serverVersion=8.0"

        steps:
            -   name: Set variables
                shell: bash
                env:
                    BRANCH: ${{ inputs.branch }}
                run: |
                    if [ "$BRANCH" == "1.12" ]; then
                        echo "USE_LEGACY_POSTGRES_SETUP=yes" >> $GITHUB_ENV
                    else
                        echo "USE_LEGACY_POSTGRES_SETUP=no" >> $GITHUB_ENV
                    fi

            -   name: "Checkout (With Branch)"
                if: "${{ inputs.branch != '' }}"
                uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.branch }}

            -   name: "Checkout"
                if: "${{ inputs.branch == '' }}"
                uses: actions/checkout@v4

            -   name: Build application
                uses: SyliusLabs/BuildTestAppAction@v2.4
                with:
                    build_type: "sylius"
                    e2e_js: "yes"
                    database_version: "8.0"
                    php_version: "8.2"
                    symfony_version: "6.4.*"
                    node_version: ${{ inputs.node }}
                    chrome_version: stable
                    
            -   name: "Run javascript linter"
                run: yarn lint

