name: Packages

on:
    workflow_call:
        inputs:
            branch:
                description: "Branch"
                required: false
                type: string
                default: ""
            php:
                description: "PHP version"
                required: true
                type: string
            symfony:
                description: "Symfony constraint"
                required: false
                type: string
                default: ""
            orm:
                description: "Doctrine ORM constraint"
                required: false
                type: string
                default: ""
            unstable:
                description: "Use unstable dependencies"
                required: false
                type: boolean
                default: false
            ignore_failure:
                description: "Don't fail on error (unstable only)"
                required: false
                type: boolean
                default: false

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        name: "PHP ${{ inputs.php }}, Symfony ${{ inputs.symfony }}${{ inputs.orm != '' && format(', ORM {0}', inputs.orm) || '' }}"
        timeout-minutes: 25

        env:
            COMPOSER_ROOT_VERSION: "dev-main"
            SYMFONY_VERSION: "${{ inputs.symfony }}"
            DOCTRINE_ORM_VERSION: "${{ inputs.orm }}"
            UNSTABLE: ${{ inputs.unstable && 'yes' || 'no' }}

        steps:
            -   name: "Checkout (With Branch)"
                if: "${{ inputs.branch != '' }}"
                uses: actions/checkout@v4
                with:
                    ref: ${{ inputs.branch }}

            -   name: "Checkout"
                if: "${{ inputs.branch == '' }}"
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ inputs.php }}"
                    coverage: none

            -   name: Restrict Symfony version
                if: inputs.symfony != ''
                run: |
                    composer global config --no-plugins allow-plugins.symfony/flex true
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^2.4"
                    composer config extra.symfony.require "${{ inputs.symfony }}"

            -   name: Get Composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache Composer
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-symfony-${{ inputs.symfony }}-"
                    restore-keys: |
                        "${{ github.run_id }}-${{ runner.os }}-${{ hashFiles('composer.json') }}-symfony-${{ inputs.symfony }}-"

            -   name: Install Robo
                run: |
                    wget https://github.com/consolidation/Robo/releases/latest/download/robo.phar
                    chmod +x robo.phar && sudo mv robo.phar /tmp/robo
                    
            -   name: "Run pipeline"
                continue-on-error: ${{ inputs.ignore_failure }}
                run: find src/Sylius -mindepth 3 -maxdepth 3 -type f -name composer.json -exec dirname '{}' \; | sed -e 's/src\/Sylius\///g' | sort | jq  --raw-input . | jq --slurp . | jq -c . | xargs -0 /tmp/robo ci:packages

