name: Upmerge PR

on:
    schedule:
        -
            cron: "0 2 * * *"
    workflow_dispatch: ~

permissions:
    contents: write
    pull-requests: write

jobs:
    upmerge:
        runs-on: ubuntu-latest
        if: github.repository == 'Sylius/Sylius'
        name: "Upmerge PR"
        timeout-minutes: 5
        strategy:
            fail-fast: false
            matrix:
                include:
                    -
                        base_branch: "1.12"
                        target_branch: "1.13"
                    -
                        base_branch: "1.13"
                        target_branch: "1.14"
                    -
                        base_branch: "1.14"
                        target_branch: "2.0"
                    -
                        base_branch: "2.0"
                        target_branch: "bootstrap-shop"
                    -
                        base_branch: "2.0"
                        target_branch: "symfony-7"
                    -
                        base_branch: "2.0"
                        target_branch: "payment-request"

        steps:
            -
                uses: actions/checkout@v4
                with:
                    ref: ${{ matrix.target_branch }}

            -
                name: Checkout temporary branch
                run: |
                    git checkout -b temp-upmerge-branch

            -
                name: Reset upmerge branch
                run: |
                    git fetch origin ${{ matrix.base_branch }}:${{ matrix.base_branch }}
                    git reset --hard ${{ matrix.base_branch }}

            -
                name: Check for changes between branches
                id: check_diff
                run: |
                    git fetch origin ${{ matrix.target_branch }}:${{ matrix.target_branch }}
                    if git diff --quiet ${{ matrix.target_branch }}; then
                        echo "No changes detected."
                        echo "no_changes=true" >> $GITHUB_ENV
                    else
                        echo "Changes detected."
                        echo "no_changes=false" >> $GITHUB_ENV
                    fi

            -
                name: Create Pull Request
                if: env.no_changes == 'false'
                uses: peter-evans/create-pull-request@v4
                with:
                    token: ${{ secrets.SYLIUS_BOT_PAT }}
                    title: '[UPMERGE] ${{ matrix.base_branch }} -> ${{ matrix.target_branch }}'
                    body: |
                        This PR has been generated automatically.
                        For more details see [upmerge_pr.yaml](/Sylius/Sylius/blob/1.13/.github/workflows/upmerge_pr.yaml).
                        
                        **Remember!** The upmerge should always be merged with using `Merge pull request` button.
                        
                        In case of conflicts, please resolve them manually with usign the following commands:
                        ```
                        git fetch upstream
                        gh pr checkout <this-pr-number>
                        git merge upstream/${{ matrix.target_branch }} -m "Resolve conflicts between ${{ matrix.base_branch }} and ${{ matrix.target_branch }}"
                        ```
                        
                        If you use other name for the upstream remote, please replace `upstream` with the name of your remote pointing to the `Sylius/Sylius` repository.
                        
                        Once the conflicts are resolved, please run `git merge --continue` and push the changes to this PR.
                    branch: "upmerge/${{ matrix.base_branch }}_${{ matrix.target_branch }}"
                    delete-branch: true
                    base: ${{ matrix.target_branch }}

            -
                name: No changes found
                if: env.no_changes == 'true'
                run: echo "No changes between ${{ matrix.base_branch }} and ${{ matrix.target_branch }}. Skipping PR creation."
